job_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('jobs.urls')),
    path('',include('adminapp.urls')),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from jobs.views.jobseeker import *
from jobs.views.recruiter import *
from jobs.views.home import *


app_name = "jobs"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='searh'),
   

    path('recruiter/dashboard', include([
       
        path('', DashboardView.as_view(), name='recruiter-dashboard'),
        path('all-applicants', ApplicantsListView.as_view(), name='recruiter-all-applicants'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='recruiter-dashboard-applicants'),
        path('update-application-status/<str:action>/<int:applicant_id>/', ManageApplicatStatusView.as_view(), name='update-application-status'),
        path('recruiter/jobs/<int:job_id>/delete/',delete_job_view, name='recruiter-jobs-delete'),
    ])),


    path('recruiter-profile-add/', AddRecruiterProfileView.as_view(), name='recruiter-profile-add'),
    path('recruiter-profile-view/', RecruiterProfileDetailView.as_view(), name='recruiter-profile-view'),
    path('recruiter-profile-edit/', RecruiterProfileEditView.as_view(), name='recruiter-profile-edit'),
    path('search/jobseekers/', SearchJobSeekersView.as_view(), name='search-jobseekers'),
     
     

    path('apply/<int:job_id>/', ApplyJobView.as_view(), name='apply-job'),
    path('applied-jobs/', AppliedJobsListView.as_view(), name='applied-jobs'),
    path('jobs', JobListView.as_view(), name='jobs'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('recruiter/jobs/create', JobCreateView.as_view(), name='recruiter-jobs-create'),
    path('recruiter/jobs/<int:job_id>/edit', UpdateJobView.as_view(), name='recruiter-jobs-edit'),
    path('jobs', JobListView.as_view(), name='jobs'),


    
    path('jobseeker-profile-add/', AddProfileView.as_view(), name='jobseeker-profile-add'),
    path('jobseeker-profile-edit/', ProfileUpdateView.as_view(), name='jobseeker-profile-edit'),
    path('jobseeker-profile-view/', ProfileDetailView.as_view(), name='jobseeker-profile-view'),
   
     
     
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

jobs/forms.py
from django import forms
from .models import *


class JobseekerProfileUpdateForm(forms.ModelForm):
    resume = forms.FileField(
        label='Resume',
        required=False,
        widget=forms.FileInput(
            attrs={'placeholder': 'Upload Resume', 
                   'accept': 'application/pdf, application/msword'
                   }),
    )
    profile_picture = forms.ImageField(
        label='Profile Picture',
        required=False,
        widget=forms.FileInput(
            attrs={'placeholder': 'Profile Picture', 
                   'accept': 'image/jpg, image/png'
                   }),

    )
    def __init__(self, *args, **kwargs):
        super(JobseekerProfileUpdateForm, self).__init__(*args, **kwargs)

        if self.instance and self.instance.resume:
            self.fields['resume'].initial = self.instance.resume
            
        self.fields['title'].widget.attrs.update(
            {
                'placeholder': 'Title',
            }
        )
        self.fields['bio'].widget.attrs.update(
            {
                'placeholder': 'Bio',
            }
        )
        self.fields['skills'].widget.attrs.update(
            {
                'placeholder': 'Skills',
            }
        )
        self.fields['education'].widget.attrs.update(
            {
                'placeholder': 'Educational Details',
            }
        )
        self.fields['experience'].widget.attrs.update(
            {
                'placeholder': 'Experience',
            }
        )
        self.fields['phone_number'].widget.attrs.update(
            {
                'placeholder': 'Mobile',
            }
        )
        self.fields['address'].widget.attrs.update(
            {
                'placeholder': 'Address',
            }
        )
        self.fields['state'].widget.attrs.update(
            {
                'placeholder': 'State',
            }
        )
        self.fields['place'].widget.attrs.update(
            {
                'placeholder': 'Location',
            }
        )

    class Meta:
        model = JobSeekerUpdateProfile
        fields = [
            "title", "bio", "skills",
            "education","experience","resume","phone_number",
            "address","state","place","profile_picture"
        ]


class RecruiterProfileUpdateForm(forms.ModelForm):
    profile_picture = forms.ImageField(
        label='Profile Picture',
        required=False,
        widget=forms.FileInput(
            attrs={'placeholder': 'Profile Picture', 
                   'accept': 'image/jpg, image/png'
                   }),

    )
    def __init__(self, *args, **kwargs):
        super(RecruiterProfileUpdateForm, self).__init__(*args, **kwargs)

        self.fields['designation'].widget.attrs.update(
            {
                'placeholder': 'Designation',
            }
        )
        self.fields['company_name'].widget.attrs.update(
            {
                'placeholder': 'Company Name',
            }
        )
        self.fields['company_description'].widget.attrs.update(
            {
                'placeholder': 'Description',
            }
        )
        self.fields['company_location'].widget.attrs.update(
            {
                'placeholder': 'Location',
            }
        )
        self.fields['industry'].widget.attrs.update(
            {
                'placeholder': 'Industry',
            }
        )
        self.fields['established_year'].widget.attrs.update(
            {
                'placeholder': 'Established Year',
            }
        )
    class Meta:
        model = RecruiterUpdateProfile
        fields = [
            "designation","company_name","company_description",
            "company_location","industry","established_year",
            "profile_picture"
        ]


class JobPostingForm(forms.ModelForm):
    class Meta:
        model = JobListing
        exclude = ('recruiter', 'posted_at','status',)

    def is_valid(self):
        valid = super(JobPostingForm, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        job = super(JobPostingForm, self).save(commit=False)
        if commit:
            job.save()
        return job



class ApplyJobForm(forms.ModelForm):
    class Meta:
        model = JobApplication
        fields = ['resume', 'cover_letter']

    def __init__(self, *args, job_id=None, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.job_id = job_id
        self.user = user

    def save(self, commit=True):
        instance = super().save(commit=False)
        if self.job_id:
            instance.job_listing_id = self.job_id
        if self.user:
            instance.job_seeker_id = self.user.id
        if commit:
            instance.save()
        return instance

jobs/views/home.py
import requests,re,random
from django.shortcuts import get_object_or_404,render,redirect
from django.db.models import Q
from django.http import Http404
from django.views import View
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy,reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from jobs.decorators import user_is_jobseeker
from django.views.generic import ListView, DetailView
from jobs.forms import ApplyJobForm
from jobs.models import *
from bs4 import BeautifulSoup


class HomeView(ListView):
    # model = JobListing
    # template_name = 'home.html'
    # context_object_name = 'jobs'
    # ordering = ['-posted_at']
    
    # def get_queryset(self):
    #     queryset = self.model.objects.order_by(*self.ordering)
    #     return queryset[:6]
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     trendings = self.model.objects.filter(posted_at__month=timezone.now().month).order_by(
    #                                                                          '-posted_at')[:3]
    #     context['trendings'] = trendings
    #     return context
    model = JobCategory
    template_name = 'home.html'
    context_object_name = 'categories'
    ordering = ['category']  # Sort categories alphabetically
    paginate_by = 8  # Show 5 categories per page

    def get_context_data(self, **kwargs):
        """Add categories and trending categories if needed."""
        context = super().get_context_data(**kwargs)
        
        # Get first 5 categories for home page
        context['home_categories'] = JobCategory.objects.order_by(*self.ordering)[:5]

        context['blogs'] = self.get_blogs()
        
        return context
    
    def get_blogs(self):
        url = "https://www.naukri.com/blog/"
        response = requests.get(url)

        if response.status_code == 200:
            soup = BeautifulSoup(response.text, "html.parser")
            blog_elements = soup.find_all("article", class_="post-card")

            blogs = []
            base_url = "https://www.naukri.com"

            for blog in blog_elements:
                title_tag = blog.find("h2")
                link_tag = blog.find("a", class_="post-card-image-link")
                desc_tag = blog.find("p")
                date_tag = blog.find("time")
                
                # Extract background-image URL
                image_div = blog.find("div", class_="post-card-image")
                image_url = None

                if image_div and "style" in image_div.attrs:
                    style_attr = image_div["style"]
                    match = re.search(r'url\((.*?)\)', style_attr)
                    if match:
                        image_url = match.group(1).strip('"').strip("'")

                title = title_tag.text.strip() if title_tag else "No Title"
                link = link_tag["href"] if link_tag else "#"
                desc = desc_tag.text.strip() if desc_tag else "No description available"
                date = date_tag.text.strip() if date_tag else "Unknown Date"

                # Ensure absolute URL for blog link
                if link.startswith("/"):
                    link = base_url + link

                # Use placeholder if image is missing
                if not image_url:
                    image_url = "default-blog-image.jpg"

                blogs.append({
                    "title": title,
                    "link": link,
                    "desc": desc,
                    "date": date,
                    "image": image_url,
                })
            
            # Shuffle blogs to display different ones each time
            random.shuffle(blogs)
            return blogs[:3]  # Show only 4 blogs
        return []
        
class MoreCategoriesView(ListView):
    model = JobCategory
    template_name = 'admin:add_categories.html'  
    context_object_name = 'categories'
    ordering = ['category']
    paginate_by = 10  # Show 10 categories per page

    def dispatch(self, request, *args, **kwargs):
        """Redirect superusers to the admin category page."""
        if request.user.is_superuser:
            return redirect('adminapp:add-category')  # Redirect to admin category management
        return super().dispatch(request, *args, **kwargs)


class SearchView(ListView):
    """
       Jobseekers can search jobs based on location and title
    """
    model = JobListing
    template_name = 'jobs/search.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        location_query = self.request.GET.get('location', '')
        title_query = self.request.GET.get('title', '')
        query = Q(location__icontains=location_query) & Q(title__icontains=title_query)
        return self.model.objects.filter(query)  
                                         

class JobListView(ListView):
    """
       List the posted jobs
    """
    model = JobListing
    template_name = 'jobs/jobs.html'
    context_object_name = 'jobs'
    paginate_by = 5
    ordering = ['-posted_at']  

    def get_queryset(self):
        return super().get_queryset()


class JobDetailsView(DetailView):
    """
       Jobseekers and recruiters can see the job details
    """
    model = JobApplication
    template_name = 'jobs/details.html'
    context_object_name = 'job'
    pk_url_kwarg = 'id'

    def get_object(self, queryset=None):
        obj = get_object_or_404(JobListing, id=self.kwargs.get(self.pk_url_kwarg))
        return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            raise Http404("Job doesn't exists")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)
    

@method_decorator(login_required(login_url=reverse_lazy('accounts:login')), name='dispatch')
@method_decorator(user_is_jobseeker, name='dispatch')
class ApplyJobView(View):
    """
       jobseekers can apply the jobs
    """
    def get(self, request, job_id):
        form = ApplyJobForm(job_id=job_id, user=request.user)
        return render(request, 'jobs/apply_job.html', {'form': form, 'job_id': job_id})

    def post(self, request, job_id):
        form = ApplyJobForm(request.POST, request.FILES, job_id=job_id, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('jobs:jobs-detail', id=job_id)
        else:
            return render(request, 'jobs/apply_job.html', {'form': form, 'job_id': job_id})




@method_decorator(login_required(login_url=reverse_lazy('accounts:login')), name='dispatch')
class AppliedJobsListView(ListView):
    model = JobApplication
    template_name = 'jobs/applied_jobs_list.html'
    context_object_name = 'applied_jobs'
    paginate_by = 5  

    def get_queryset(self):
        # Get applied jobs for the current user
        return JobApplication.objects.filter(job_seeker=self.request.user).distinct()

jobs/views/jobseeker.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import UpdateView , CreateView, DetailView
from jobs.forms import *
from jobs.models import *
from django.contrib import messages





@method_decorator(login_required(login_url=reverse_lazy('accounts:login')), name='dispatch')
class AddProfileView(CreateView):
    """
       Jobseekers can add their profiles
    """
    model = JobSeekerUpdateProfile
    form_class = JobseekerProfileUpdateForm
    template_name = 'jobs/jobseeker/add_profile.html'
    success_url = reverse_lazy('jobs:jobseeker-profile-view')

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, 'Profile created successfully.')
        return super().form_valid(form)


@method_decorator(login_required(login_url=reverse_lazy('accounts:login')), name='dispatch')
class ProfileDetailView(DetailView):
    """
       Jobseekers can view their profile
    """
    model = JobSeekerUpdateProfile
    template_name = 'jobs/jobseeker/view_profile.html'
    context_object_name = 'profile'

    def get_object(self, queryset=None):
        return get_object_or_404(JobSeekerUpdateProfile, user=self.request.user)
    
    

@method_decorator(login_required(login_url=reverse_lazy('accounts:login')), name='dispatch')
class ProfileUpdateView(UpdateView):
    """
       Jobseekers can update their profile
    """
    model = JobSeekerUpdateProfile
    form_class = JobseekerProfileUpdateForm
    template_name = 'jobs/jobseeker/edit_profile.html'
    success_url = reverse_lazy('jobs:jobseeker-profile-view')
    
    def get_object(self, queryset=None):
        return JobSeekerUpdateProfile.objects.get(user=self.request.user)
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.instance = self.get_object()
        return form

templates/jobs/jobseeker/add_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Jobseeker-Add Profile
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Add Profile</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger alert-dismissable">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    <strong>{{ field.name }} {{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                    <form id="job-main-form" method="post" action="" class="job-add-form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="title">Title</label>
                                <input id="title" name="title" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="bio">Bio</label>
                                <textarea id="bio" name="bio" rows="5" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 form-group">
                                <label for="education">Education</label>
                                <input id="education" name="education" type="text" placeholder="e.g. BCA,MCA..."
                                       class="form-control">
                            </div>
                            <div class="col-lg-6 form-group">
                                <label for="experience">Experience</label>
                                <input id="experience" name="experience" type="text" placeholder="e.g. 1 year"
                                       class="form-control">
                                
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="skills">Skills</label>
                                <textarea id="skills" name="skills" rows="5" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 form-group">
                                <label for="phone_number">Mobile</label>
                                <input id="phone_number" name="phone_number" type="text"
                                       class="form-control">
                            </div>
                            <div class="col-lg-6 form-group">
                                <label for="address">Address</label>
                                <input id="address" name="address" type="text"
                                       class="form-control">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 form-group">
                                <label for="state">State</label>
                                <input id="state" name="state" type="text" 
                                       class="form-control">
                            </div>
                            <div class="col-lg-6 form-group">
                                <label for="place">Place</label>
                                <input id="place" name="place" type="text" 
                                       class="form-control">
                            </div>
                            
                        </div>
                        <div class="row">
                            <div class="col-lg-6 form-group">
                                <label for="resume">Resume</label>
                                <input id="resume" name="resume" type="file" 
                                       class="form-control">
                            </div>
                            <div class="col-lg-6 form-group">
                                <label for="profile_picture">Profile Picture</label>
                                <input id="profile_picture" name="profile_picture" type="file" class="form-control">
                            </div>
                            
                        </div>
                        
                        <div class="row">
                            <div class="col-lg-12 text-center">
                                <hr>
                                <button type="submit" class="btn btn-outline-white-primary"><i class="fa fa-magic"></i>
                                    Save Profile
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/jobseeker/view_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Jobseeker- View Profile
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">View Profile</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container emp-profile">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img" id="profile-img-container">
                            {% if profile.profile_picture %}
                                <img id="profile-img" src="{{ profile.profile_picture.url }}" alt="" style="width: 180px; height: 180px;"/>
                            {% else %}
                                <img id="profile-img" src="/media/jobseeker_profile_pictures/default.jpg" alt="" style="width: 150px; height: 150px;"/>
                            {% endif %}
                            
                        </div> 
                          
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        {{profile.user}}
                                    </h5>
                                    <h6>
                                        {{profile.title}}
                                    </h6>
                                   
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                            
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <a href="{% url 'jobs:jobseeker-profile-edit' %}" class="btn btn-outline-white-secondary">
                            <i class="fa fa-magic"></i>Update
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4" style=" padding: 15px; border-radius: 8px; margin-bottom: 20px;">
                        <h5 style="color: blue;">About Me</h5>
                        <p>{{profile.bio}}</p>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent" >
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>User</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{profile.user}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{profile.user.email}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Mobile</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{profile.phone_number}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Address</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{profile.address}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Place</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{profile.place}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>State</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{profile.state}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Education</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{profile.education}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Experience</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{profile.experience}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Skills</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{profile.skills}}</p>
                                            </div>
                                        </div>  
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Resume</label>
                                            </div>
                                            <div class="col-md-6">
                                                {% if profile.resume %}
                                                  <a href="{{ profile.resume.url }}" target="_blank">{{ profile.resume.name }}</a>
                                                  {% else %}
                                                  No resume uploaded
                                                {% endif %}
                                            </div>
                                        </div>  
                                        
                            </div>
                            
                            
                        </div>
                    </div>
                </div>
            </form>           
        </div>
    </section>

{% endblock %}